"""add spotify_track_id to playlist_songs

Revision ID: 21c67b0d2bf0
Revises: 64a8c7dd130f
Create Date: 2026-03-31 17:15:52.118410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21c67b0d2bf0'
down_revision: Union[str, Sequence[str], None] = '64a8c7dd130f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist_songs', sa.Column('spotify_track_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist_songs', 'spotify_track_id')
    # ### end Alembic commands ###
