"""add spotify_searched_at to songs

Revision ID: 7795b47c503c
Revises: e36b1a723652
Create Date: 2026-04-16 18:39:42.948807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7795b47c503c'
down_revision: Union[str, Sequence[str], None] = 'e36b1a723652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('spotify_searched_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'spotify_searched_at')
    # ### end Alembic commands ###
