"""add synced_at to playlists

Revision ID: 860ede019435
Revises: 21c67b0d2bf0
Create Date: 2026-04-01 20:09:40.952011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '860ede019435'
down_revision: Union[str, Sequence[str], None] = '21c67b0d2bf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('synced_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'synced_at')
    # ### end Alembic commands ###
