"""rename synced_at to pushed_at

Revision ID: e36b1a723652
Revises: 860ede019435
Create Date: 2026-04-01 20:22:52.949813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e36b1a723652'
down_revision: Union[str, Sequence[str], None] = '860ede019435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('pushed_at', sa.DateTime(), nullable=True))
    op.drop_column('playlists', 'synced_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('playlists', 'pushed_at')
    # ### end Alembic commands ###
